export default [
  {
    name: 'Bernardo',
    slack: '@bernardo',
    hero: 'Hammerizer',
    avatar: 'hammerizer-avatar.png',
    class: 'Engineer',
    superpower: 'Matter Bender',
    xp: 1,
  },
  {
    hero: 'Omega',
    slack: '@diegoferreira',
    class: 'Pilot',
    superpower: 'Pathfinder',
  },
  {
    hero: 'The Source & The Honey',
    slack: '@rmariuzzo',
    class: 'Pilots',
    superpower: 'creates a force field',
  },
  {
    hero: 'Juan',
    slack: '@jenriquejr',
    class: 'Pilot',
    superpower: 'creates portals',
  },
  {
    hero: 'Dylan',
    slack: '@dylancoffey',
    class: 'Diplomat',
    superpower: '???? (undiscovered)',
  },
  {
    hero: 'William',
    slack: '@williamcabrera',
    class: 'Diplomat',
    superpower: 'Mind reader',
  },
  {
    hero: 'Zero',
    slack: '@kdemoya',
    class: 'Psychic',
    superpower: 'Teletransportation',
    xp: 2,
  },
  {
    hero: 'Canto',
    slack: '@noah.muth',
    class: 'Psychic',
    superpower: 'intuitive aptitude',
  },
  {
    hero: 'The Envisioner',
    slack: '@ryanchartrand',
    class: 'Psychic',
    superpower: 'Summons energy blasts',
  },
  {
    hero: 'Animator',
    slack: '@luisfonseca',
    class: 'Psychic',
    superpower: 'Bring life to inanimate objects',
  },
  {
    hero: 'Bench',
    slack: '@jacek.lawniczak',
    class: 'Psychic',
    superpower: 'Remote viewing.',
  },
  {
    hero: 'Tiny',
    slack: '@ben',
    class: 'Soldier',
    superpower: 'super stealth',
  },
  {
    hero: 'CodeRocker',
    slack: '@diego.seghezzo',
    class: 'Soldier',
    superpower: 'provides energy power to others',
  },
  {
    hero: 'Zeus',
    slack: '@szymon.karnecki',
    class: 'Soldier',
    superpower: 'Striking with thunderbolts',
    xp: 1,
  },
  {
    hero: 'Sleight',
    slack: '@bart',
    class: 'Demolitionist',
    superpower: 'Exploding Cards',
    xp: 1,
  },
  {
    hero: 'Manifestation',
    slack: '@jake',
    class: 'Demolitionist',
    superpower: 'Absorption of powers',
  },
  {
    hero: 'Alchemix',
    slack: '@josh',
    class: 'Medic',
    superpower: 'Heal damage from one person and deal it to another (the ol\' "heal-and-deal")',
  },
  {
    hero: 'Asc',
    slack: '@joel',
    class: 'Medic',
    superpower: 'Electronics Mindhacking',
  },
]
